# Use an official Node.js runtime as a base image
FROM node:20.9-alpine

# Set the working directory inside the container
WORKDIR /app
COPY . /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port that the app will run on
EXPOSE 9000

# Command to run the application
CMD ["npm", "start"]